### ISSUE TITLE
X2 pre-trained

### ISSUE THREAD

**Issue by Burgerting** [skycrapers/TecoGAN-PyTorch#25]
hello,
Thanks for your upload X2 reimplementation!

Can you provide X2 pre-trained model?
I try to train X2 and follow your training steps, ​but the result is terrible.
Or, can you share how do you train X2?

Besides, REDS and Vid4  testing datasets only have X4 LR, can you provide your implemented dataset

THX!!!

**Comment by jndeng** [comment]
Hi, @Burgerting

Yes, I've uploaded the [2xSR model](https://drive.google.com/file/d/1XN5D4hjNvitO9Kb3OrYiKGjwNU0b43ZI/view) trained on the REDS dataset, as well as the [training settings](https://github.com/skycrapers/TecoGAN-PyTorch/blob/master/experiments_BD/TecoGAN/TecoGAN_REDS_2xSR_2GPU/train.yml).

As regards your second question, if you are using BD degradation, you don't need LR data since the code will generate it on the fly according to GT. For BI mode, you can use the MATLAB script [here](https://github.com/skycrapers/TecoGAN-PyTorch/blob/master/scripts/generate_lr_bi.m) to generate the 2x LR.
