### ISSUE TITLE
Reason for padding in forward function of FRNet

### ISSUE THREAD

**Issue by mehranjeelani** [skycrapers/TecoGAN-PyTorch#6]
Hi...Thanks for sharing this code. What is the reason for padding the flow image if it is not multiple of 8 in the forward function of FRNet?
```
 # estimate lr flow (lr_curr -> lr_prev)
        lr_flow = self.fnet(lr_curr, lr_prev)

        # pad if size is not a multiple of 8
        pad_h = lr_curr.size(2) - lr_curr.size(2) // 8 * 8
        pad_w = lr_curr.size(3) - lr_curr.size(3) // 8 * 8
        lr_flow_pad = F.pad(lr_flow, (0, pad_w, 0, pad_h), 'reflect')
```

**Comment by jndeng** [comment]
Thanks for your interest!

The reason is that we need to ensure the size of the estimated flow 'lr_flow' is the same as that of 'lr_curr'.

The flow estimation network fnet has 8x downsampling, so if the input image is not a multiple of 8, the estimated flow image will end up smaller than the input image. This is why we need to pad the flow image.
